version: '2'
services:
    springrol-mongodb:
        container_name: springrol-mongodb
        image: mongo:3.2.3
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/springrol/mongodb/:/data/db/
