version: '2'
services:
    springrol-mongodb:
        container_name: springrol-mongodb
        image: mongo:3.2.3
        ports:
            - "27017:27017"
        command: mongos --configdb springrol-mongodb-config
    springrol-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    springrol-mongodb-config:
        image: mongo:3.2.3
        container_name: springrol-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
